### ISSUE TITLE
Can I save animated gif?

### ISSUE THREAD

**Issue by gjslkjs** [t0rakka/mango#50] opened 2020-01-03 09:08 UTC
I want to save multiple mango Surfaces to an animated gif file, but I could not find a way.
How could I save animated GIF? Also can I set the details of the animated GIF? (frame delay for each frame separately, loop count, local palette, transparent index etc..)

**Comment by t0rakka** [comment] 2020-01-03 09:13
There is no API for saving animations.

**Comment by t0rakka** [comment] 2020-01-03 09:16
The whole gif-encoder thing is a fairly new addition (by a feature request) and added color quantizer and paletted dithering into the library. I recommend some other library for encoding animations unless I find motivation to add support for that (this is mostly data IMPORTING library ;)

**Comment by gjslkjs** [comment] 2020-01-03 09:24
Thank you for your kindness reply.
I'll try other library to save it.

**Comment by t0rakka** [comment] 2020-01-03 09:26
It wouldn't be technically too difficult to do the animations; it's basically just calling gif_encode_image_block in image_gif.cpp with correct parameters multiple times and writing the frame chunks. But the problem is coming up with a neat API for that.

Something long the lines of:

1. begin encode
2. for (...) add frame
3. end encode

There are questions like should be data be RGB and always quantized? Should be first frame's palette be used and all other frames mapped into that palette, or should adding a local palette for each frame be allowed. Should these be configurable by user, if so, what would that API look like?

Efficient gif animation supports updating only sub-rectangles of the full image for parts that change and stuff like that. I'll pass this for now.. :D

**Comment by t0rakka** [comment] 2020-01-03 09:30
If you want to give encoding animations a shot, the existing code should be able to do it with minimal modifications if you know exactly what your inputs are. See above 1-2-3 three step plan how it would look like. The hardest part is the gif_encode_image function and that is already done.. it's just how the existing code is called to make this happen. :)

The large(-st) amount of work is making it work with all kinds of inputs the user might have.

**Comment by t0rakka** [comment] 2020-01-03 09:45
Check the latest version I pushed a minute ago; I commented the block of code that needs to be repeated if you want to write multiple frames. Feel free to copy-paste the code to try out writing the animations.. I recommend you have the begin-add-end so that you don't have to pass a vector of surfaces or anything dumb like that (you want to encode as you go, right?).

After I find more time, I will think of nicest possible API and implement it. For me the large hassle is that I need to update all other encoder as well, even if they will do nothing with the new API.

**Comment by gjslkjs** [comment] 2020-01-03 09:51
Thank you! I found your commented line in code for gif animation!
It is a great help to me. I'll try it!

**Comment by t0rakka** [comment] 2020-01-03 09:51
Hah, simplest possible API I can think of is adding "bool last_frame = true", where default is that the first frame is the ONLY frame. If you want more frames, just pass false, until you're done, and then the last frame will also close the stream; in case of gif it will write the terminator byte.

The animation frames would by that definition always be same size, but the encoder COULD check diffs to previous frame and compute a bounding box (as optimization).

That would be so dumb, but could get the job done...

**Comment by t0rakka** [comment] 2020-01-03 09:52
If you're willing to try above API and implement it for gif.. pull requests are welcome (winks-winks). Otherwise, I do it when I get time allocated for this.

**Comment by t0rakka** [comment] 2020-01-05 23:16
Progress; made the ColorQuantizer re-entrant so that can encode more images with same network (palette). This gives option of using same palette in gif, so that don't have to have a local palette for each frame. A bit of plumbing-work behind the curtains..

**Comment by t0rakka** [comment] 2020-01-05 23:17
.. the downside is that the source image has to be converted to BGRA twice, so it's recommended that caller only passes BGRA images to begin with if want to "optimize" the process a little bit.

**Comment by t0rakka** [comment] 2020-01-08 16:42
Yeah, the comment I added worked as intended. Created a demo animated gif and it worked great. The remaining work is to create a nice interface for creating these animations.

**Comment by t0rakka** [comment] 2020-01-22 13:11
I close this for now as it's not really "Issue" that breaks anything. I'll move this to my internal "maybe-TODO" -list. As said, the prototype was super easy to write and worked great.

**Closed by t0rakka** 2020-01-22 13:11 UTC
