### ISSUE TITLE
zip crash issue

### ISSUE THREAD

**Issue by w136111526** [t0rakka/mango#22] opened 2018-12-13 06:37 UTC
When I use zip to decompress files, it's normal when there is no password, but zip files with password can't decompress. Why? My code is as follows:
        //mango::Path path("e:/test.zip/", ""); //normal
	mango::Path path("e:/test.zip/", "123456");
	File file(path, "request.json");
	int nSize = file.size();
	auto data = file.data();

**Comment by t0rakka** [comment] 2018-12-13 07:08
You must use the path as parent for the file! The PW is stored in active
parent. Should work then.

**Comment by t0rakka** [comment] 2018-12-13 07:31
// works with this test case, the password tested with was "123456"
#include <mango/mango.hpp>
using namespace mango;

int main()
{
    Path path("test.zip/", "123456");
    File file(path, "test.txt");
    Memory m = file;
    std::string s = std::string((char*)m.address, 5);
    printf("%s\n", s.c_str());
}

**Comment by t0rakka** [comment] 2018-12-13 07:33
Is it a modern zip file with AES encryption? Didn't write support for that yet. You can use the zip version < 3 encryption, which is not as strong but is already supported. I plan to eventually implement the AES since we already have the decryption routines in the library. It's just a engineering problem of hooking the two up. =)

**Comment by w136111526** [comment] 2018-12-13 07:49
I want to pack a resource file with a password. sometimes I need to load zip from a specified path, such as(e: path1 path2 test.zip) ,instead of the current path. How do I write this ?

**Comment by w136111526** [comment] 2018-12-13 10:06
Thanks very much. for example:
I want to uncompress d: \\data\\sample.zip, It has an  param.bin file, password is 123456, how should I write it?

**Comment by w136111526** [comment] 2018-12-13 12:43
Thanks ，I will try it later. Memory crash happened while extracting data like this in the morning.

**Comment by t0rakka** [comment] 2018-12-13 12:57
Ahaa.. gotcha. In that case it's probably not password related as the code throws an exception when the password is incorrect - that means your program cannot proceed to read from the buffer.

If the crash persists, check the address. Also try to validate that the returned data is correct. You can compute checksum for the non-encrypted file and compare it with the encrypted file. If the checksums don't match there is data corruption. The most likely cause for that is we let incorrect password to go through w/o throwing. If you look at the mapper_zip.cpp line 424 in master branch you see how this could happen. If this is the cause, I need to figure out the correct password validation logic ASAP.

If you can create a simple zip file which can demonstrate this problem I could take a closer look. (if this is still a problem)

**Comment by t0rakka** [comment] 2018-12-20 10:00
Checked the password verification logic: it should be conforming to the specification.

1] PKWARE Inc. APPNOTE.TXT – .ZIP File Format Specification, version 6.3.4
https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

// our check
if (keyfile[11] != (crc >> 24))

The specification says that 12th (last) byte of the keyfile should be 8 MSB of the CRC32 checksum when the password is valid one. This check works. I have a zip file where this does not hold true and I cannot remember where/who/how I got it. The only clue is that the version is > 3. 

I created zip files with all the compression tools that support it I could find and they all check out OK with the decryption code we are using. AES excluded, of course, since the AES support is still WIP.

Pretty sure this is not the cause for the problem you experienced. I'll close this issue if you cannot reproduce before 2019. ;-) Let me know if you still have a problem, I can see what is going on if you can help me to reproduce the conditions.

**Comment by w136111526** [comment] 2018-12-20 10:06
yes, zip uncompross works well, I've tried zip encryption. I'm trying to compress and save files, such as 1. jpg, 2. txt, 3. xml, into a new file.

**Comment by w136111526** [comment] 2018-12-27 09:21
hello.I want to read a zip compressed binary data, the password is 123456. Why can't I read it in this way, and how modify my code?
my code as following:
	try
	{
		std::vector<unsigned char> vData;
		FILE* pFile = fopen("e:/test.zip", "rb");
		fseek(pFile, 0, SEEK_END);
		int nSize = ftell(pFile);
		vData.resize(nSize);
		rewind(pFile);
		fread(&vData[0], 1, nSize, pFile);
		fclose(pFile);
		mango::Memory mem(vData.data(), nSize);
		mango::Path path1(mem, "123456");
		File file1(path1, "test.jpg");
		int nSize1 = file1.size();
		auto data1 = file1.data();
	}
	catch (const std::exception& e)
	{
		cout << e.what() << endl;
	}

**Comment by t0rakka** [comment] 2018-12-28 01:46
There is no container-write support, you need external tool like 7z, snitch, zip, rar, etc.

**Comment by w136111526** [comment] 2018-12-28 01:50
Thanks, I have solved the issue

**Closed** 2018-12-28 01:51 UTC
