### ISSUE TITLE
Bitmap loading slows down when there are lots of files in a directory

### ISSUE THREAD

**Issue by jarnoh** [t0rakka/mango#74] opened 2020-11-16 09:50 UTC
I'm loading images from individual files in directory with simple `mango::Bitmap("/some/where/foo.jpg")`.  

What I'm seeing is that the loading of the image is very fast, but if I have few thousands of files in the directory, the code spends more time wastefully listing the directory contents than actual decoding.  

(this is not the latest master, but the relevant parts of the code seem same to me)
```
#0	0x00000001024d152c in mango::filesystem::Path::Path(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) at /Users/jarnoh/git/mango/source/mango/filesystem/path.cpp:22
#1	0x00000001024d1798 in mango::filesystem::Path::Path(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) at /Users/jarnoh/git/mango/source/mango/filesystem/path.cpp:17
#2	0x000000010250add8 in mango::filesystem::File::File(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) at /Users/jarnoh/git/mango/source/mango/filesystem/file.cpp:26
#3	0x000000010250b564 in mango::filesystem::File::File(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) at /Users/jarnoh/git/mango/source/mango/filesystem/file.cpp:17
#4	0x000000010252fbe0 in (anonymous namespace)::load_surface(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mango::Format const*) at /Users/jarnoh/git/mango/source/mango/image/surface.cpp:204
#5	0x000000010252fd20 in mango::Bitmap::Bitmap(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mango::Format const&) at /Users/jarnoh/git/mango/source/mango/image/surface.cpp:561
#6	0x000000010252fd7c in mango::Bitmap::Bitmap(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mango::Format const&) at /Users/jarnoh/git/mango/source/mango/image/surface.cpp:562
```

Inside Path constructor, I found weird getIndex call, which lists all the files:

https://github.com/t0rakka/mango/blob/a1c89d1de5836e99b6ed90846b63dd45f8b6fd51/source/mango/filesystem/path.cpp#L21

What's the logic behind getIndex?  Simply commenting it out makes things screaming fast.

Similar issue reproducible with mango/example/jpeg_benchmark: 

````
jarnoh@kuikka example % ./image/jpeg_benchmark_test testdata/foo.jpg
image: 960 x 640 (76 KB)
----------------------------------------------
                load         save             
----------------------------------------------
libjpeg:      10.4 ms      17.2 ms 
stb:           8.2 ms      41.5 ms 
jpgd:          8.1 ms       9.7 ms 
mango:         1.2 ms       1.8 ms 
jarnoh@kuikka example % seq -f testdata/dummy%g.txt 1 100000 | xargs touch 
jarnoh@kuikka example % ./image/jpeg_benchmark_test testdata/foo.jpg      
image: 960 x 640 (76 KB)
----------------------------------------------
                load         save             
----------------------------------------------
libjpeg:       8.1 ms      15.6 ms 
stb:           6.6 ms      41.2 ms 
jpgd:          7.4 ms      10.0 ms 
mango:       492.1 ms       1.0 ms 
```

**Comment by t0rakka** [comment] 2020-11-16 11:45
I think the problem here is that I often use Path object as "root folder" for file access so the indexing only happens once so never ran into this.. but now that you point it out it's super obvious. =)

`
Path path("project/data/")
Bitmap bitmap(path, "images/foo.jpg");
`

But you're right; it shouldn't scan many times in use pattern which is very common. The best way would be the do indexing only when required or requested by the user.

I think this is a good opportunity to separate the file indexer and path mapping; I'll take a crack at it.

**Comment by t0rakka** [comment] 2020-11-16 11:51
One way I can see it working is getIndex() method for the Path.. just need to check don't break anything, such as recursive mapping. At least I have a super-extensive regression test for this code so that's a good start.. :D :D 

The getIndex() could be callable by user.. also, called internally when iterating or accessing the Path, possibly caching the index.

Other possibility is to track the Path with file notify and do a callback when something changed so that user can update his external index. There is one hazard with this: iterating while a change occurs, so I'd probably only have iterating capability in the external FileIndex object the Path returns. If something changed, ask for a new index.

Corner cases like this keep popping into mind.. have to keep it simple.. =D

**Comment by t0rakka** [comment] 2020-11-16 12:22
Branch path_indexing has a simple fix; haven't tested yet, YOLO.. it's quite simple: don't index at constructor. The indexing is done in "updateIndex()" method which is called when the index is accessed. The result is cached and dirty flag is cleared..

I didn't add any of the file notify stuff in there, it's something that the user can do himself. If he gets a notify that something changed he can ask for a new index (by creating a new Path object). This workflow could be cleaner but I'll leave it for another time.

This *should* fix the issue but meanwhile I run some regressions and do some timings did it help.. the problem you described seemed fairly straightforward to fix, so hope didn't miss the problem with this "fix" .. :D : D

**Comment by t0rakka** [comment] 2020-11-16 12:28
Played around with JPEG HW decoder in RPi4, it's kinda cool, but can't decode all files.. but in our parser we can detect what the HW can decode and what it can't. The way it works is that we have to submit work to the decoder and get a notify when the result is available. Intel also has HW decoder in their CPUs but access is a bit awkward.. same thing with other embedded SoCs and hardware.. writing unified support for everything like that is a big chore.

I also tested Apple's hw decoder, it's blazing fast when you decode into GPU surface. If you decode into RAM it's slow AF. So HW decoder API should also have paths for decoding into GPU surfaces in different APIs, systems and so on.. and some kind of indicators what are fast paths and so on..

.. and that is the reason why I like software decoder; much less hassle.. even if lose in speed to hardware decoders.. but all the same, working on some kind of solution to the problem, might take 10 years at this rate..

NOTE: If I were a hardware manufacturer I would shout from the rooftops how to use my great hardware.. but everyone is burying their great stuff under ten layers of crap.. why???

(off-topic rant ends)

**Comment by t0rakka** [comment] 2020-11-16 13:35
Did some internal cleaning on top of everything else. Let me know what happens.

**Comment by t0rakka** [comment] 2020-11-16 20:25
Reproduced (was easy) and fixed. I did some code cleaning as extra bonus. 

I slightly hate how the updateIndex() is lingering in there, getIndex() as public member function would have been kind of nice way to go about it but this way the API remains exactly as it was and the Path is iterable which is convenient so we'll proceed with this.

Close this when convenient and I'll merge to master. :D

**Comment by t0rakka** [comment] 2020-11-18 08:55
Tested & fixed. Thanks for the head's up JM! :D

**Closed by t0rakka** 2020-11-18 08:55 UTC
