### ISSUE TITLE
Image Process

### ISSUE THREAD

**Issue by w136111526** [t0rakka/mango#35] opened 2019-05-09 02:39 UTC
Hello, I want to use Surface to write a Chinese watermark on a picture. Can mango support it?

**Comment by w136111526** [comment] 2019-05-09 02:41
Does mango currently support GIF dynamic graph loading and saving?

**Comment by t0rakka** [comment] 2019-05-09 07:23
You must do the rendering into loaded picture yourself. If the watermark has alpha channel, doing the blending in 32 bit BGRA or RGBA is fairly trivial.

**Comment by t0rakka** [comment] 2019-05-09 07:31
Dynamic gif loading? I don't know what that is.. if you mean can the code load animated gifs, the answer is: yes and no. The code CAN read animated gifs but this functionality is not exposed at this time because there is no API to do that in mango. 

Random access to the gif animation frame is not practical, the only API that would be efficient would be to ask for number of frames and "give me next frame" -kind of approach. I might allow the ::decode() member function of ImageDecoder to decode next frame, and wrap around back to beginning.. something like that would work. Then add the frame count into the ImageHeader so that you could know the decoder has access to multiple frames.

If you look at the image_gif.cpp, you notice how the code specifically ignores the END OF GIF marker because animated gifs would signal error that the marker is missing (when it is not - it will come after all of the animation frames..)

Don't be surprised if this functionality magically appears into the code in near future. I can't promise a fixed deadline as have other stuff to work on.. but you might be surprised eventually. :)

**Comment by w136111526** [comment] 2019-05-09 09:03
I'm using FreeImage, which can load animations and edit modifications, all I want to see if mango supports

**Comment by t0rakka** [comment] 2019-05-09 09:08
Editing: no.

**Comment by t0rakka** [comment] 2019-05-09 17:07
Added gif animation decoding support. You can keep calling ::decode() and it will decode frames, then wrap around after the last frame. it supports palette extraction mode.

The way the animation in GIF works is that it decodes on top of previous image, but for now I wrote the code so that the decoder keeps it's own internal image buffer where it decodes.. then blits the result out. This way the caller can decode into any buffer without worrying about what was in that buffer/memory location before. This is not as efficient as directly decoding on top of the old buffer in client-managed memory but let's get started with this approach as it is harder to use "wrong".

Palette extraction mode and BGRA decoding cannot be mixed together as that would require decoding into both 8 bit and 32 bit internal target buffers. I might fix that wart as well, but let's first get a taste how this interface works.

Frame numbering: it is impossible to know in advance if the GIF file will have more than one frame before you decode the first frame.. so header cannot report if the file has animation and if so, how many frames. The GIF file just stores frames until the file is depleted.. to know the number of frames the whole animation has to be decoded. I'll try to figure out if there are ways to work around this..

I could add a mechanism to report decoding result.. currently decode "returns" null, but the API could be changed to return "ImageDecodeStatus", which could return all kinds of interesting information about the decoder (what format were used, if it was direct decode, what blitter was used, if NEON, SSE2, AVX, etc. were used.. information about the internal storage format like if image was compressed using RLE, DCT, Huffman, Arithmetic, etc..). The point being the decode status could tell if there are more frames and when the animation wrapped around and that sort of diagnostic information that might be useful.

I added animated_gif example into the mango-examples repository: it basically loads a gif files and plays the animation back at 60 fps. This might be too high rate for some animations and too slow for others, also, frame repetition is not supported yet.. some animations use that to implement freeze frames etc.. but this is the first version I got working so it's what it is. Improvements may follow.

**Comment by t0rakka** [comment] 2019-05-09 17:09
I have skimmed the extension chunks, they might have the fps information and frame information in them.. more specs reading will be done shortly & code will be improved based on the data I manage to extract from the specification. Like said before, we got the bare bones decoding going now, yay... party...

**Comment by t0rakka** [comment] 2019-05-09 21:51
OK; the all frames of the gif must be decoded to know the animation length. That's that & can't be fixed. The best I can do is return some diagnostic data from the decode so that the caller can decide what to do with the information.

There is a mechanism to detect if the gif only has a single frame so that further decode calls won't burn too much CPU. Not decided if it should do nothing on further calls or just blit out the internal buffer (this later choice seems more intuitive so that the decode works like other codecs do; I just optimize the CPU usage a little bit).

I could add saving, too, but saving into gif is not really something that is generally very useful for most.. also remember that with gif format you have to modify the original 8 bit index data with the original palette anything else is less efficient (you would need a color quantizer for starters if your source data was RGB). I wouldn't want to force any specific quantizer in there.. and generally color quantization is something I would prefer to keep outside of scope of this library. If you insist doing something like that the Kohonen / Neuquant is pretty decent, you might want to throw in some dithering to go with it, though, when resolving the final indices). A bit off-topic.. but covers the  read_gif -add_watermark - write_gif use case you had in mind. I'd just watermark in the palette space (so you must be able to map RGB into color index, which is fairly easy so I won't go into too much detail about that).

I'll close this issue if there aren't any major action items left..

**Comment by w136111526** [comment] 2019-05-10 01:22
I looked at the GIF animation decoding, but I don't know how to use it. Could you write me a simple example?

**Comment by t0rakka** [comment] 2019-05-10 07:04
I wrote example; it is in mango-examples repository in gif_animation/ folder.

**Comment by w136111526** [comment] 2019-05-10 09:33
![QQ截图20190510173210](https://user-images.githubusercontent.com/29495143/57517506-94eede00-7349-11e9-8d2c-3f7dfd694784.png)
 When I played the GIF with demo, I played back the memory allocation error, and how do I get the GIF frame number?

**Comment by t0rakka** [comment] 2019-05-10 09:55
You don't get the frame number until there is some feedback mechanism to return it. I might add ImageDecodeStatus which will be returned from ::decode but for now it doesn't exist.

**Comment by w136111526** [comment] 2019-05-10 09:57
I'm now trying to write the surface encoded GIF locally. Can I do that?

**Comment by t0rakka** [comment] 2019-05-10 10:05
Regarding the error: I have macOS and Linux to test with me at the moment and the animation worked. I made it run 250 Hz and it kept running and looping OK.

Try to pull latest example and library code, rebuild from scratch. If the problem still persists try debug build if you could get more information about the error. I will try on Windows / Visual Studio tomorrow.

I fixed some issues in the code, which have been fixed in the latest commits so it might be that you are simply experiencing bugs I fixed already. If not, then have to find out what's up.

**Comment by t0rakka** [comment] 2019-05-10 10:07
You can write into some other format, per frame, something like result-000.png, result-001.png and so on.. of course, you can't know when the animation loops yet so try with 200 as max frame number (the animation dude.gif should be something more than 100 frames or so).

I don't have gif encoder. I could write one bug as I explained before already it would require a color quantizer if the input is RGB color and don't want to force a specific one on the users and so on. It's more of a design dilemma than how to do it; the code itself is fairly trivial. It's just how the clients might want to call it is the part that I haven't really wanted to solve. xD

**Comment by w136111526** [comment] 2019-05-10 10:14
I used to develop environments when Windows / vs 2015, Mango supports a lot of image formats. I usually use it with OpenCV. Can GIF save pictures in rgba format? I found that when I used FreeImage, Setting up transparent channels is a problem.

**Comment by t0rakka** [comment] 2019-05-10 10:17
One thing I could do is that I just ask the caller for a palette and index data; so it would be your job to provide them. This would require the Surface to know about palettes.. in older version of library that was the case, but then the Palette had to be carried with all surfaces (it was in the PixelFormat as dynamically allocated array). 

I more or like decided that indexed color is kinda MEH in 2012, when I dropped the support. I kind of brought palette support back so that files that have indexed images, the palette and index data can be extracted out but the actual blitter/pixelformat infrastructure  don't know anything about it. It's kind of a back-door for getting the data, but the library itself doesn't want to know about it.

OK, so decode() does support palette extraction. I could sneak in another backdoor for the encode() to accept palette and index data so that it works both ways. But this requires a bit special arrangements.. at this point it might already be worthwhile to have IndexedSurface to capture palette and force the image data to be 8 bit (for 1..8 bit indexed data). It kind of gets convoluted at this point which is the reason why I dropped the support in the first place..

**Comment by t0rakka** [comment] 2019-05-10 10:17
No, GIF can only save 256 color indexed images.

**Comment by t0rakka** [comment] 2019-05-10 10:22
The inputs are:

BGRA palette[256]
u8 image[width * height]

Where each u8 is index into the palette. That is what is stored in the GIF file (the index data is compressed).

If you have RGB image, you must choose 256 colors, then lookup what palette entry (index) has best match for the RGB color of pixel you will be encoding as palettrized image index.

I previously mentioned Kohonen / Neuquant, which gives very good results for color quantization. This algorithm can turn RGB color image into indexed image. There are other algorithms like median cut and so on but they are pretty crap. I also mentioned that you might want some dithering to make the indexed image look better (you are basically trading spatial resolution to color resolution).

It's something I want to keep out of scope of this library.. I used to have these things but deprecated them years ago since didn't have any use for the code for 10+ years. I feel that stuff is obsolete. .but I still support loading old image formats as that is fairly simple thing so no point dropping the support.

**Comment by t0rakka** [comment] 2019-05-10 10:25
For now my main concern is the crash you experienced with Windows. Let me know if the problem still persists after building with latest commits so that I know to check out what's happening with Windows build.

**Comment by w136111526** [comment] 2019-05-10 10:30
Ok, I 'll recompile the mango later, and I 'll try it on the Linux machine to see if there's a crash.

**Comment by w136111526** [comment] 2019-05-10 10:35
Is the memory allocation failure due to Windows / vs 2015/x86 environment still reporting just a screenshot error? The error is as follows:
0x763218A2(in mango-test. EXE) has an unprocessed exception: Microsoft C++ exception: STD: bad_alloc, located at memory position 0x0113 F454.

**Comment by w136111526** [comment] 2019-05-10 10:39
I 've just changed the platform to x64, and the program works.

**Comment by t0rakka** [comment] 2019-05-10 11:05
That helps; I can check out what's happening with 32 bit build. The file isn't that massive, 360 KB or so, the memory mapping should succeed just fine. If there is something, it will be found.

**Comment by t0rakka** [comment] 2019-05-10 15:30
Tested on Windows machine on x86 (32 bit) and reproduced the problem. Debugger did show the width and height were 45000, which would have allocated 1.9 GB if that would have worked on the 32 bit. :)

It was quite easy fix; the restart address for animation was incorrect - I went back to complete beginning of the file instead of where the frames begin. The fix is in this commit:

https://github.com/t0rakka/mango/commit/d0bca1136b81ef033d81d74834e25ca27ec1f4e4

**Comment by t0rakka** [comment] 2019-05-14 08:59
GIF animation support: added (tested: working).
GIF writing: not supported.

I'll close this as there are no action items left. I might improve the API later to get the decode status but that goes into TODO list. Closing the issue for now as the new feature is working.

**Closed by t0rakka** 2019-05-14 08:59 UTC

**Comment by w136111526** [comment] 2019-05-14 09:09
Thanks to you, I can now use CxImage to implement giff writing, but it is mainly used under Windows rather than across platforms.
